<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cart</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5a68c155-3468-4345-b530-6a3eb3bfddd1</testSuiteGuid>
   <testCaseLink>
      <guid>14779f15-897c-4478-94ac-e02b1c1e8678</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Single product/Calculation of cart item subtotal price</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>67a1f401-ae79-41e7-83dc-55d1dbf70036</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Single product/Calculation of cart total price</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d8f52d63-6b1f-486f-9f7e-92584d242421</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Single product/Clear cart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3cb97b69-74fb-46d4-999f-45d20b15e67d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Single product/Order and check out using coupon</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ad4c4772-76ed-4df7-bf4b-925400008a04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Single product/Order and check out</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>700d6e4e-307e-448a-aa19-8127c96f0056</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c0d16db-73f9-40b6-851f-f777b8bae206</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>672fb4fd-4f00-452f-a8b4-62df3d124ffc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51421ccf-ad17-4e9f-9d5a-18e620ee93bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c863fc5-9dab-4c4a-881c-d478032e26c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f8f1ad7-8f79-44a0-b33d-fc78e90e9e1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1106ce6b-eba2-406b-ac41-b29f53a45fcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cb399d2-1bfc-408e-8254-a03dd003f568</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>840d634e-1132-4714-b198-87fdc6546a4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Multiple Products/Calculation of cart item subtotal price</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>edc4bd98-0bbf-462a-abac-13092d3adee8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Multiple Products/Calculation of cart total price</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1683b25b-f80b-47cb-8920-a0a4ff9eb16c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Multiple Products/Clear cart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>84b6005b-51fa-4c16-8412-6f4171eba554</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Multiple Products/Order and check out multiple products</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e316e7e7-cde2-4ff4-84f7-e4519410ab7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11d04582-8ad7-4ddf-bff2-138e344fd545</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Cases/Multiple Products/Order and check out</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d114563c-a934-4c02-b67c-374e6492b91d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3388c9f-5c6d-4dca-b574-113fd63f2724</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e1aef8f-9a9c-47e7-9a24-4459600a0d94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c69e5743-8ea4-41b8-8b5d-65760c8724ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e4df06b-22f3-457b-85ed-6c7d01efea64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9068477f-1d9a-4134-9dfe-cb7877fbc45a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1d2c26a-45f2-42d1-81d8-d3d61ba213db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b99e08a3-d81b-46ee-9c57-0b99ba34bd73</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
