<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emptyCartInfo</name>
   <tag></tag>
   <elementGuidId>f7f67b57-f3d8-485c-9920-75c4d78bbdc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.cart-empty</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
