<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemPrice</name>
   <tag></tag>
   <elementGuidId>5e53ced6-7dbb-4894-9a6c-d175b6c7be6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-title=&quot;Price&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
