<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>totalItemPrice</name>
   <tag></tag>
   <elementGuidId>b8966e40-5c4c-4b9d-8e70-87b6758dc1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-title=&quot;Total&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
